# Generated by Django 4.2.2 on 2023-06-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_manufacturer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='verified_manufacturer',
            field=models.BooleanField(default=False),
        ),
    ]
