# Generated by Django 4.2.2 on 2023-06-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_squadron'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squadron',
            old_name='Spacecraft',
            new_name='spacecraft',
        ),
    ]
